apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    env: poc
spec:
  project: default
  source:
    repoURL: 'https://github.com/DzeCin/argo-applications'
    path: 'cert-manager/subChart'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-poc.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
