apiVersion: v2
name: traefik
description: Sub chart for traefik
type: application
version: 26.1.0
appVersion: "1.16.0"
dependencies:
  - name: traefik
    version: 26.1.0
    repository: https://traefik.github.io/charts