apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  labels:
    env: poc
spec:
  project: default
  source:
    repoURL: 'https://github.com/DzeCin/argo-applications'
    path: kube-prom-stack/subChart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-poc.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true