postgres-operator:
  image:
    registry: registry.opensource.zalan.do
    repository: acid/postgres-operator
    tag: v1.10.1
    pullPolicy: "IfNotPresent"
  configTarget: "OperatorConfigurationCRD"
  podLabels:
    app: postgres
  enableJsonLogging: true
  configGeneral:
    enable_crd_registration: true
    crd_categories:
    - "all"
    set_memory_request_to_limit: true
  configKubernetes:
    cluster_domain: cluster.local
    # additional labels assigned to the cluster objects
    cluster_labels:
      application: spilo
    cluster_name_label: cluster-name
    enable_cross_namespace_secret: true
    enable_init_containers: true
    enable_pod_antiaffinity: true
    enable_pod_disruption_budget: true
    pdb_name_format: "postgres-{cluster}-pdb"
    pod_antiaffinity_preferred_during_scheduling: false
    pod_antiaffinity_topology_key: "kubernetes.io/hostname"
    secret_name_template: "{username}.{cluster}.credentials.{tprkind}.{tprgroup}"
    spilo_privileged: false

  # configure resource requests for the Postgres pods
  configPostgresPodResources:
    default_cpu_limit: 750m
    default_cpu_request: 500m
    default_memory_limit: 500Mi
    default_memory_request: 250Mi
    min_cpu_limit: 250m
    min_memory_limit: 250Mi
  configDebug:
    debug_logging: false
    enable_database_access: true
  configLoggingRestApi:
    api_port: 8080
    cluster_history_entries: 1000
    ring_log_lines: 100

  rbac:
    create: true
    createAggregateClusterRoles: false

  serviceAccount:
    create: true
  podServiceAccount:
    name: "postgres-pod"

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: postgres
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role/infra
            operator: Exists